name: Build

on:
  release:
    types: [created]
  workflow_dispatch:
# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: oneflow
  TAG: ${{ github.sha }}

jobs:
  build-test-with-tf:
    name: "Build test with TF"
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        tf-version: [2.1.0, 2.2.0, 2.3.0, 2.4.0]
    defaults:
      run:
        working-directory: test-with-tf
    env:
      IMAGE: test-with-tf
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      # 1.2 Buid and push image to ACR
      - name: Build image
        run: |
          docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE-${{matrix.tf-version}}:$TAG" --build-arg TF_VERSION=${{matrix.tf-version}} .
      - name: Push image to ACR
        run: |
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
