name: Build CUDA LLVM

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "update-dependencies-pr"
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "*.sh"
  # pull_request:
  #   paths:
  #     - ".github/workflows/build.yml"
  #     - "docker/**"
  #     - "build.sh"

concurrency:
  group: llvm-cuda-${{ github.ref }}
  cancel-in-progress: true

env:
  REGION_ID: cn-beijing
  ACR_REGISTRY: registry.cn-beijing.aliyuncs.com
  ACR_NAMESPACE: oneflow
  DOCKER_HUB_NAMESPACE: oneflowinc

jobs:
  build_img:
    name: ${{ matrix.policy }}_${{ matrix.platform }}_${{ matrix.tag-suffix }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        tag-suffix: ["llvm13_cuda11.2"]
        include:
          - tag-suffix: "llvm13_cuda11.2"
            BASE_IMAGE: "cuda:11.2.2-cudnn8-devel-ubuntu20.04"
    env:
      DOCKER_REPO: "${{ matrix.tag-suffix }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: ./build.sh
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ env.COMMIT_SHA }}
            ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ env.COMMIT_SHA }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./cuda-llvm
          build-args: |
            POLICY
            PLATFORM
            BASEIMAGE
            DEVTOOLSET_ROOTPATH
            PREPEND_PATH
            LD_LIBRARY_PATH_ARG
