name: Build hf-transformers-pytorch-deepspeed

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/transformers.yml"
      - "hf-transformers-pytorch-deepspeed/**"
  release:
    types: [created]
  workflow_dispatch:
# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-beijing
  ACR_REGISTRY: registry.cn-beijing.aliyuncs.com
  ACR_NAMESPACE: oneflow
  DOCKER_HUB_NAMESPACE: oneflowinc

jobs:
  build-hf-transformers-pytorch-deepspeed:
    name: "Build test with pytorch"
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        img:
          - {
              tag: "huggingface/transformers-pytorch-deepspeed-latest-gpu",
              rename: "huggingface--transformers-pytorch-deepspeed-latest-gpu",
            }

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{matrix.img.rename}}:latest
            ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{matrix.img.rename}}:latest
            ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{matrix.img.rename}}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{matrix.img.rename}}:latest
          cache-to: type=inline
          context: hf-transformers-pytorch-deepspeed
          build-args: |
            PYTORCH_TAG=${{matrix.img.tag}}
