name: Build oneflow-nightly

on:
  release:
    types: [created]
  workflow_dispatch:
# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: oneflow

jobs:
  build-oneflow-nightly:
    name: "Build test with pytorch"
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        tag-suffix: ["cuda10.2", "cuda11.1"]
        include:
          - tag-suffix: "cuda10.2"
            cuda-version: "10.2"
            ONEFLOW_PACKAGE_NAME: oneflow
            ONEFLOW_PIP_INDEX: https://staging.oneflow.info/branch/master/cu102
          - tag-suffix: "cuda11.1"
            ONEFLOW_PACKAGE_NAME: oneflow
            ONEFLOW_PIP_INDEX: https://staging.oneflow.info/branch/master/cu111
    defaults:
      run:
        working-directory: oneflow
    env:
      IMAGE: oneflow
      TAG: nightly-${{ matrix.tag-suffix }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      # 1.2 Buid and push image to ACR
      - name: Set env
        run: |
          echo FULL_TAG="$REGISTRY/$NAMESPACE/$IMAGE:$TAG" >> $GITHUB_ENV
      - name: Build image
        run: |
          docker build --tag "${{ env.FULL_TAG }}" --target official \
            --build-arg CUDA_VERSION=${{matrix.cuda-version}} \
            --build-arg ONEFLOW_PIP_INDEX="${{matrix.ONEFLOW_PIP_INDEX}}" .
            --build-arg ONEFLOW_PACKAGE_NAME="${{matrix.ONEFLOW_PACKAGE_NAME}}" .
      - name: Push image to ACR
        run: |
          docker push "${{ env.FULL_TAG }}"
