name: Build oneflow-devcontainer

on:
  workflow_dispatch:
# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: oneflow

jobs:
  build-oneflow-devcontainer:
    name: "Build devcontainer"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        tag-suffix: ["cuda11.1", "llvm12"]
        include:
          - tag-suffix: "cuda11.1"
            CUDA_VERSION: "11.1"
            LLVM_VERSION: ""
            build-target: devcontainer-cuda
          - tag-suffix: "llvm12"
            CUDA_VERSION: ""
            LLVM_VERSION: 12
            build-target: devcontainer-llvm
          - tag-suffix: "llvm13"
            CUDA_VERSION: ""
            LLVM_VERSION: 13
            build-target: devcontainer-llvm
    env:
      IMAGE: devcontainer
      TAG: ${{ matrix.tag-suffix }}
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 1.2 Build and push image to ACR
      - name: Set env
        run: |
          echo ACR_TAG="$REGISTRY/$NAMESPACE/$IMAGE:$TAG" >> $GITHUB_ENV
          echo DOCKERHUB_TAG="oneflowinc/$IMAGE:$TAG" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKERHUB_TAG }}
            ${{ env.ACR_TAG }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_TAG }}
          cache-to: type=inline
          target: ${{ matrix.build-target }}
          build-args: |
            CUDA_VERSION=${{matrix.CUDA_VERSION}}
            LLVM_VERSION=${{matrix.LLVM_VERSION}}
          file: oneflow/Dockerfile
      - name: Push image to ACR
        run: |
          docker push "${{ env.ACR_TAG }}"
