name: Build OPENVINO dev image

on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - ".github/workflows/build.yml"
  #     - "docker/**"
  #     - "build.sh"

concurrency:
  group: llvm-cuda-${{ github.ref }}
  cancel-in-progress: true

env:
  REGION_ID: cn-beijing
  ACR_REGISTRY: registry.cn-beijing.aliyuncs.com
  ACR_NAMESPACE: oneflow
  DOCKER_HUB_NAMESPACE: oneflowinc

jobs:
  build_img:
    name: Build ${{ matrix.tag-suffix }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag-suffix: "openvino_ubuntu20_dev_no_samples"
            BASE_IMAGE: "openvino/ubuntu20_dev_no_samples"
          - tag-suffix: "openvino_ubuntu20_dev_no_samples_2021.4.2"
            BASE_IMAGE: "openvino/ubuntu20_dev_no_samples:2021.4.2"
          - tag-suffix: "openvino_ubuntu18_dev_no_samples_2021.2"
            BASE_IMAGE: "openvino/ubuntu18_dev_no_samples:2021.2"
    env:
      DOCKER_REPO: "${{ matrix.tag-suffix }}"
      BASE_IMAGE: "${{ matrix.BASE_IMAGE }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.${{env.REGION_ID}}.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
            ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
            ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline
          context: ./openvino
          build-args: |
            BASE_IMAGE
